<p>Contacts don't fail because of astigmatism, keratoconus, or dry eye. They fail because most fittings never dig deep enough to account for those conditions in the first place. Hard-to-fit contact lenses in Forest Hills exist for exactly this reason, and the right fit usually depends less on the eye and more on who is doing the fitting.</p>
<p>At Austin Optics, that person is Mark Kimyagarov, a licensed <a href="{{ route('meet-the-team') }}">optician</a> who has spent over 15 years working through cases that other practices pass on. This guide walks through what actually makes an eye hard to fit, what the process looks like when it is done properly, and why patients who gave up on contacts years ago sometimes end up wearing them comfortably again.</p>

<figure class="post-figure">
    <img src="{{ asset('images/uploads/2026/05/Computer-Vision.jpg') }}" alt="" width="1000" height="667">
</figure>

<h2><strong>What Does "Hard to Fit" Mean?</strong></h2>
<p>A hard-to-fit eye is one in which a standard soft lens does not sit correctly, remain comfortable, or provide clear vision, usually because of the eye's shape, its tear film, or a corneal condition. The most common causes are keratoconus, high or irregular astigmatism, chronic dry eye, and corneas reshaped by surgery.</p>
<p>Astigmatism happens when the cornea curves unevenly rather than forming a smooth sphere, which scatters light and blurs vision unless the lens is shaped to counteract it. Keratoconus happens when the cornea thins over time and bulges into a cone-like shape, and standard lenses simply cannot hold a stable position on that surface. Dry eye adds a separate problem. Since a lens needs a healthy tear layer underneath it to stay comfortable, eyes that do not produce enough tears or produce poor-quality ones will reject almost any lens that touches the cornea directly.</p>
<h2><strong>Why the Fitting Fails at Other Practices</strong></h2>
<p>Most contact lens appointments are built around a handful of standard lens brands and a fifteen-to twenty-minute visit. That works fine for average eyes. It falls apart for anyone whose cornea does not match the assumptions on which those lenses were designed.</p>
<p>We have seen this pattern several times, and it usually goes like this: a patient tries one or two soft toric lenses, the fit rotates, or the vision stays blurry, and the provider concludes that contacts "just aren't for" that patient. What actually happened is narrower. A limited set of lens designs was tried, without the corneal mapping needed to understand why they failed or what a better-shaped lens would need to look like. Fitting a genuinely hard-to-fit eye usually requires equipment most general practices do not keep on hand, along with access to specialty lens labs that build lenses to exact measurements rather than pulling from a standard inventory.</p>
<h2><strong>How Mark Approaches a Difficult Fitting</strong></h2>
<p>Every specialty and hard-to-fit contact lens patient at Austin Optics works directly with Mark, not a rotating staff member. He has fitted patients through keratoconus, severe astigmatism, post-LASIK complications, and dry eye cases that had already failed elsewhere, and that repetition matters more than it sounds like it should. Recognizing which lens design fits a particular corneal shape is a skill built through volume and years of experience.</p>
<p>The process starts with corneal topography, a mapping technology that measures the exact curvature and irregularities across the eye's surface. That data rules out any guesswork others might have concluded. Instead of trying lenses at random, Mark narrows the options to the two or three designs based on the actual shape of the cornea, then fine-tunes from there using a trial lens and a follow-up check. For Forest Hills contact lens specialist patients who have already had disappointing fittings elsewhere, that difference in approach is usually the first thing they notice.</p>
<h2><strong>Matching the Right Lens to the Right Eye</strong></h2>
<p>There is no single best lens for hard-to-fit eyes. The right choice depends on the specific condition, its severity, and the patient's eyes' response to the trial fitting.</p>
<p>Scleral lenses cover the entire cornea and rest on the white part of the eye. They are often the top choice for conditions such as keratoconus, post-surgery corneas, and moderate-to-severe dry eye because they keep the eye moist throughout the day. Rigid gas-permeable lenses remain a strong option for irregular astigmatism and can outlast soft lenses by a wide margin. However, they take longer to adjust to. Hybrid lenses have a firm center for clear vision and a soft edge for comfort, which gives you sharp vision like RGP lenses but with an easier adjustment. For a deeper look at how <a href="{{ route('blog.post', 'scleral-lenses-for-keratoconus-dry-eye') }}">scleral lenses address keratoconus and severe dry eye</a>, it is worth reviewing the specifics of how fitting is measured and adjusted.</p>
<h2><strong>What a Fitting Appointment Looks Like</strong></h2>
<p>A hard-to-fit consultation runs longer than a routine <a href="{{ route('contact-lens-exams') }}">contact lens exam</a>, and that extra time is where the accuracy comes from. The visit starts with an evaluation of corneal health, tear film quality, and eyelid function, followed by topography mapping to capture the eye's exact surface. From there, Mark fits a trial lens, checks how it moves and settles, and tests vision with it in place before making any adjustments.</p>
<p>Most patients need at least one follow-up visit before the fit is finalized, and that is normal rather than a sign something went wrong. Specialty lenses are built to tight tolerances, so small adjustments after the first fitting are part of getting it right, not a delay.</p>
<h2><strong>Insurance, Cost, and Turnaround</strong></h2>
<p>Specialty lens fittings are sometimes classified as medically necessary rather than purely elective, which means they may be covered under a medical insurance plan even when a vision plan alone would not cover them. Coverage depends heavily on the specific diagnosis and the individual plan, so it is worth <a href="{{ route('insurances') }}">checking your insurance</a> before the appointment rather than after. Austin Optics also accepts Medicare directly.</p>
<p>Turnaround for specialty lenses depends on the design, since scleral and custom RGP lenses are built to order rather than pulled from stock. Most orders are ready within the practice's standard 5-to-7-business-day window once the final measurements are confirmed, though unusually complex cases can take a bit longer.</p>
<h2><strong>Why Choose Austin Optics for Hard-to-Fit Contacts</strong></h2>
<p>Patients travel from across Queens and the other boroughs for this specifically because volume builds judgment that a single training course cannot. Mark has fitted enough difficult corneas to recognize patterns quickly, and he is the one person handling the case from the first measurement through every follow-up. Nobody gets passed between staff members mid-process. Combined with on-site corneal topography and access to scleral, RGP, hybrid, and custom soft lens designs, that continuity tends to separate a fitting that finally works from the ones that already failed elsewhere.</p>
<h2><strong>Frequently Asked Questions</strong></h2>
<h3><strong>Can I wear contact lenses if I have astigmatism?</strong></h3>
<p>In most cases, yes. Mild to moderate astigmatism is usually correctable with a soft toric lens. Higher or irregular astigmatism often needs a toric RGP or hybrid lens, which holds its shape more precisely than a soft lens can.</p>
<h3><strong>What is the best contact lens option for keratoconus?</strong></h3>
<p>Scleral lenses are the most common recommendation because they vault over the irregular cornea entirely and rest on the sclera, avoiding contact with the thinned or bulging area. RGP lenses are also used for milder cases, depending on the severity of the keratoconus.</p>
<h3><strong>Why do my contacts feel uncomfortable even though my prescription is correct?</strong></h3>
<p>Discomfort usually points to a fit or tear film issue rather than a prescription problem. A lens can be optically correct and still sit poorly on the eye or dry out faster than your tear film can keep up with, both of which a standard exam without topography can miss.</p>
<h3><strong>I was told I'm not a candidate for contacts. Is that actually true?</strong></h3>
<p>Not always, and often not at all. That conclusion is often based on a limited set of lens types being tried rather than a full evaluation of your specific corneal needs. A hard-to-fit consultation with corneal mapping can identify options a standard fitting would never reach.</p>
<h3><strong>Are scleral lenses right for me?</strong></h3>
<p>Scleral lenses tend to work well for keratoconus, post-surgical corneas, irregular astigmatism, and moderate to severe dry eye. Whether they are the right choice for your eyes specifically depends on your corneal shape and tear film, which the fitting evaluation assesses.</p>
<h3><strong>How long does a hard-to-fit contact lens fitting take?</strong></h3>
<p>The initial evaluation and trial lens fitting typically takes longer than a standard contact lens exam, often close to an hour. Most patients need at least one follow-up visit before the final lenses are ordered.</p>
<h3><strong>Do you accept Medicare for contact lens fittings?</strong></h3>
<p>Yes. Austin Optics accepts Medicare, and specialty lens fittings may also qualify for coverage under medical insurance, depending on your diagnosis. Call ahead, and the coverage can be checked before your visit.</p>
<h3><strong>How soon will I get my new lenses?</strong></h3>
<p>Most orders are ready within 5 to 7 business days once your final measurements are confirmed. Custom scleral and RGP lenses are built to order, so complex cases can occasionally take a little longer.</p>
<p>Austin Optics is located at 72-20 Austin Street, Forest Hills, NY 11375, open Tuesday through Saturday. Call (718) 261-8655 to schedule a hard-to-fit contact lens consultation with Mark, or <a href="{{ route('contact-us') }}">book your appointment online</a> to get started.</p>
