<p>Most people who wear glasses every day have never actually shopped for eyewear. They&#8217;ve bought whatever a big-box retailer had in stock that fit their insurance benefit. That&#8217;s a different experience from what happens at a boutique that curates its own collection, and it&#8217;s worth understanding why before you spend real money on your next pair.</p>
<p>At Austin Optics in Forest Hills, the eyewear wall is personally chosen by <a href="{{ route('meet-the-team') }}">Iris</a>, a licensed optician with more than 30 years in the industry, including time at a Park Avenue boutique and a long run at a Brooklyn Heights practice before she returned to Queens. She carries Silhouette, Face à Face, Chopard, Anne et Valentin, and Lafont, and she&#8217;ll tell you flat out that she&#8217;s turned away plenty of other brands to keep that list short.</p>
<figure class="post-figure">
    <img src="{{ asset('images/uploads/2026/05/high-performance-lenses.jpg') }}" alt="" width="1024" height="683">
</figure>
<h2>Why Austin Optics Carries Only a Few Eyewear Brands</h2>
<p>A shop that stocks forty brands is optimizing for choice while one that stocks five is optimizing for quality, and that&#8217;s a deliberate trade-off.</p>
<p>Every frame Iris orders has to earn its place in the case. She&#8217;s looking at how the acetate is finished, whether the hinges are engineered to hold up after years of daily wear, and whether the brand&#8217;s design philosophy translates into a frame someone will still want to wear in five years. A lot of eyewear on the market fails one or more of those tests. The frames that make it into the shop have already been filtered through three decades of watching what holds up and what doesn&#8217;t.</p>
<p>That&#8217;s also why the sunglasses and prescription frames come from the same collections. If you&#8217;ve read through the <a href="{{ route('sunglasses') }}">prescription sunglasses page</a>, you&#8217;ve already seen Lafont, Silhouette, and Chopard listed there. It&#8217;s the same reasoning applied to a different lens purpose.</p>
<h2>Silhouette: Austrian Titanium and the Rimless Standard</h2>
<p>Silhouette is the brand most associated with rimless eyewear, and there&#8217;s a real engineering story behind that reputation. The company manufactures its own titanium in a factory in Linz, Austria, and assembles nearly every component in-house. This is unusual in an industry where most brands outsource production to keep costs down.</p>
<p>The rimless design is an aesthetic choice and more than that. Because there&#8217;s no frame holding the lens edges, the glasses weigh a fraction of what standard eyewear weighs, some models come in under two grams. Titanium is also naturally nickel-free, so it doesn&#8217;t trigger the skin reactions that some metal alloys cause on the nose and behind the ears.</p>
<p>Silhouette suits someone who wants their glasses to correct their vision without becoming the first thing people notice about their face. It&#8217;s a quiet, precise kind of luxury, built around comfort and engineering rather than statement-making design.</p>
<h2>Face à Face: French Design With a Point of View</h2>
<p>Face à Face sits at the opposite end of the spectrum from Silhouette, and that contrast is exactly why Austin Optics carries both.</p>
<p><a href="{{ route('meet-the-team') }}">Founded in Paris in 1995</a> by a small team with backgrounds in architecture and design, Face à Face treats each pair of glasses as a sculptural object. The brand builds its acetate collections from raw organic material and finishes them by hand in its own workshop in the Jura region of France, an area with a long history of eyewear craftsmanship. Selected pieces carry the Origine France Garantie certification, which verifies that the shaping, polishing, and assembly all happened on French soil.</p>
<p>What sets Face à Face apart visually is the layering. Two colors, two materials, deliberate asymmetry. A frame might combine a matte finish with a glossy one, or pair an unexpected color against a neutral base. This is a brand for someone who wants their glasses to read as a personal style statement.</p>
<h2>Chopard: Swiss Precision Meets Fine Jewelry Detail</h2>
<p>Chopard&#8217;s eyewear shares the same DNA as its watches and fine jewelry, and that lineage shows in the details.</p>
<p>Silhouette is all about making glasses lighter. Face à Face focuses on sculpted acetate designs. Chopard, on the other hand, adds metal details inspired by its famous jewelry collections. Their frames have faceted fronts and jeweled accents and the finishing touches come from years of high jewelry craftsmanship. It&#8217;s the kind of frame where the craftsmanship becomes obvious the moment you hold it rather than just look at it from across the room.</p>
<p>Chopard suits a patient who wants their eyewear to read as fine jewelry as much as vision correction. It&#8217;s a smaller share of the collection, but for the right patient, nothing else in the case compares.</p>
<h2>Anne et Valentin and Lafont: Rounding Out the Collection</h2>
<p>Anne et Valentin, founded in Toulouse, built its identity on bold color combinations and architectural frame shapes that don&#8217;t shy away from being noticed. It&#8217;s a good option for patients who like Face à Face&#8217;s boldness but prefer a different design language.</p>
<p>Lafont has a longer history, dating back to 1923 in Paris, and its frames tend to lean toward vintage-inspired shapes reinterpreted with modern materials and color work. Patients who want something with a nostalgic, romantic quality, without it being an old design, often land on Lafont.</p>
<p>Together with the three brands above, these five collections cover a wide enough range of design philosophies that most patients find something that genuinely fits their taste, rather than settling for the closest match in a limited case.</p>
<h2>What 100% Cotton Acetate Means</h2>
<p>Acetate is the material most premium eyewear frames are made from, but not all acetate is the same quality, and this is an important detail many sites ignore.</p>
<p>Cheap plastic frames are typically injection-molded from petroleum-based plastic. They are less flexible, more prone to becoming brittle over time, and harder on sensitive skin. Cotton-based acetate, by contrast, starts as cotton fiber processed into sheets, which are then cut, shaped, and polished by hand rather than molded in a machine. The result is a material that&#8217;s more flexible, holds color and pattern better, and is generally more comfortable against the skin because it doesn&#8217;t carry the same petroleum byproducts.</p>
<p>Every frame Iris carries, across all five brands, is made from this cotton-based acetate. It&#8217;s part of why the frames feel and wear differently than what you&#8217;d find at a typical retail optical chain, and it&#8217;s a material distinction worth understanding before you compare price tags across different shops.</p>
<h2>How Iris Curates Every Collection</h2>
<p>Curation isn&#8217;t a marketing word here so much as a description of an actual process that happens twice a year when new collections come out.</p>
<p>Iris looks at hinge construction first, because that&#8217;s usually where cheaper frames fail within the first year. She checks how the acetate is finished at the edges, since rough or uneven finishing is a sign of rushed manufacturing. She considers whether a frame will look good on many face shapes and work for different prescriptions. If a style only fits one type of face, it&#8217;s not worth carrying, even if it&#8217;s well-made. If you want a deeper look at how frame shape and face shape interact, our <a href="{{ route('frame-selection') }}">face shape styling guide</a> covers that in more detail.</p>
<p>What doesn&#8217;t pass that filter doesn&#8217;t make it into the shop, regardless of how well-known the brand name is. That&#8217;s a different standard than most optical retailers use, and it&#8217;s why the collection stays small even as the brands within it remain consistent year over year.</p>
<h2>Why Choose Austin Optics</h2>
<p>The eyewear itself is only half the reason patients travel from Manhattan, Brooklyn Heights, and across Queens to shop here. The other half is that the person helping you choose a frame is the same person who curated the entire collection and will handle your prescription and lens fitting, too.</p>
<p>Every lens fitted into these frames is <a href="{{ route('lenses') }}">Crizal, Zeiss, or Varilux</a>, the same standard applied across every pair of glasses that leaves the shop, whether it&#8217;s a $200 frame or a designer piece. Austin Optics accepts Medicare and fills prescriptions from any licensed doctor, so you don&#8217;t need to switch providers to access this collection. Most orders, including designer frames fitted with premium lenses, are ready in 5 to 7 business days.</p>
<h2>Frequently Asked Questions</h2>
<h3>What makes Silhouette glasses different from other titanium frames?</h3>
<p>Silhouette manufactures its own titanium and assembles nearly all of its components in its Austrian factory, which most eyewear brands don&#8217;t do. The result is a rimless design that&#8217;s dramatically lighter than standard frames while still being durable and hypoallergenic.</p>
<h3>Is Face à Face eyewear actually handmade?</h3>
<p>Yes. The optical collections are finished by hand at the brand&#8217;s own workshop in the Jura region of France, and selected pieces carry a certification confirming that the shaping and assembly took place in France.</p>
<h3>Where can I see Chopard eyewear in Queens or NYC?</h3>
<p>Austin Optics in Forest Hills carries a curated selection of Chopard frames and sunglasses. Availability rotates with each collection, so it&#8217;s worth calling ahead if you&#8217;re looking for a specific style.</p>
<h3>What is 100% cotton acetate, and why does it matter?</h3>
<p>It&#8217;s a frame material made from processed cotton fiber rather than petroleum-based plastic. It&#8217;s more flexible, holds color better, and tends to be more comfortable against the skin than standard injection-molded plastic frames.</p>
<h3>Do you carry every model from these brands?</h3>
<p>No. Each collection is selected personally, which means you&#8217;ll see a curated subset rather than the full catalog from any single brand. What&#8217;s in the case has already been filtered for quality and fit.</p>
<h3>Can these frames be fitted with progressive or Varilux lenses?</h3>
<p>Yes. Any frame in the collection can be fitted with Varilux progressives, Zeiss lenses, or Crizal coatings, the same lens standard used throughout the practice.</p>
<h3>How do I know which brand suits my face and style?</h3>
<p>That&#8217;s part of what a fitting is for. Face shape, prescription strength, and personal style all factor into which brand and frame shape will actually work for you, and that guidance is part of every visit.</p>
<h3>Are these frames covered by insurance or Medicare?</h3>
<p>Austin Optics accepts Medicare and most major vision plans. Coverage for designer frames varies by plan, so it&#8217;s worth calling ahead to check what your specific benefit includes.</p>
<p>Austin Optics is located at 72-20 Austin Street, Forest Hills, NY 11375, open Tuesday through Saturday. <a href="{{ route('contact-us') }}">Call (718) 261-8655</a> to book a private fitting or to ask which of these collections might be worth trying on first.</p>
