<?php

return [
    '/childrens-and-adult-eye-exams-when-and-why-you-need-them/' => '/eye-vision-exams/',

    '/service/computer-vision/' => '/computer-vision/',

    '/author/admin_q3sznavb/' => '/blog/',
    '/author/admin_q3sznavb/page/2/' => '/blog/',

    '/category/eye-glasses/' => '/lenses/',
    '/category/healthy-eyes/' => '/eye-vision-exams/',
    '/category/eye-exam/' => '/eye-vision-exams/',
    '/category/eye-exam/page/2/' => '/eye-vision-exams/',

    '/tag/prescription-eye-glasses/' => '/lenses/',
    '/tag/eye-health/' => '/eye-vision-exams/',
    '/tag/eye-health/page/2/' => '/eye-vision-exams/',
    '/tag/contact-lenses-for-irregular-corneas/' => '/hard-to-fit-contact/',
    '/tag/custom-contact-lenses/' => '/hard-to-fit-contact/',
    '/tag/computer-vision-systems/' => '/computer-vision/',
    '/tag/therapy-for-myopia-control/' => '/myopia-with-atropine-eye-drop/',
    '/tag/eye-exam-do-you-need-this-holiday-season/' => '/eye-vision-exams/',
    '/tag/child-eye-test/' => '/eye-vision-exams/',
    '/tag/eye-care-for-heavy-screen-users/' => '/computer-vision/',
    '/tag/tips/' => '/blog/',
    '/tag/pediatric-eye-screening/' => '/eye-vision-exams/',
    '/tag/how-to-pick-the-best-lenses/' => '/how-to-choose-the-right-lenses-for-your-vision-and-lifestyle/',
    '/tag/premium-eyewear-brands/' => '/premium-eyewear-brands-at-austin-optics-what-makes-silhouette-face-a-face-and-chopard-different/',
    '/tag/natural-vision-than-glasses/' => '/eye-vision-exams/',
    '/tag/eyewear-for-vision-correction/' => '/lenses/',
    '/tag/blue-light-glasses/' => '/the-truth-about-blue-light-glasses-what-they-do-and-dont-do/',
    '/tag/child-might-need-glasses/' => '/9-signs-your-child-might-need-glasses/',
    '/tag/eye-vision/' => '/eye-vision-exams/',
    '/tag/eye-surgery-in-usa/' => '/navigating-eye-care-in-nyc/',
    '/tag/digital-eye-strain-exams/' => '/computer-vision/',
    '/tag/wrong-glasses-damage-your-eyes/' => '/5-signs-your-eyeglass-prescription-is-wrong/',
    '/tag/childrens-eye-exams/' => '/eye-vision-exams/',
    '/tag/screen-time-eye-checkup/' => '/computer-vision/',
    '/tag/eye-examination/' => '/eye-vision-exams/',
    '/tag/expect-during-a-vision-exam/' => '/eye-vision-exams/',
    '/tag/reading-eye-glasses/' => '/lenses/',
    '/tag/why-regular-eye-exams-are-important/' => '/eye-vision-exams/',
    '/tag/eyewear-tips-for-face-shapes/' => '/how-to-choose-the-perfect-eyeglass-frames-for-your-face-shape/',
    '/tag/find-the-right-glasses-for-your-face/' => '/how-to-choose-the-perfect-eyeglass-frames-for-your-face-shape/',
    '/tag/corrective-surgery/' => '/navigating-eye-care-in-nyc/',
    '/tag/selecting-lenses-for-daily-use/' => '/how-to-choose-the-right-lenses-for-your-vision-and-lifestyle/',
    '/tag/corneal-surgery/' => '/navigating-eye-care-in-nyc/',
    '/tag/hyperopia-treatment-in-usa/' => '/hyperopia-affects-near-vision/',
    '/tag/expert-tips-for-eye-health/' => '/eye-vision-exams/',
    '/tag/do-i-need-a-contact-lens-exam/' => '/contact-lens-exams/',
];
